### ISSUE TITLE
Begineer needs help

### ISSUE THREAD

**Issue by MrSilver122** [n-i-x/pc-autobackup#20]
Hello, i am really interested into use this feature with my Samsung NX20, but i never do any programing, i will appreciate your help to guide me about how to do that works, maybe an short video tutorial can help not jus me but a lot of other users

**Comment by n-i-x** [comment]
I haven't used this software in years and I don't even have this camera anymore. There are instructions in the README, but aside from that, if you run into issues you'll need to figure it out on your own unfortunately.
